config/routes.rb
TripPlanner::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  root to: 'entrances#home'

  match '/about', to: 'entrances#about'
  match '/contact', to: 'entrances#contact'

  resources :organizations

  resources :planners

  resources :trips

end

app/models/trip.rb
# == Schema Information
#
# Table name: trips
#
#  id          :integer          not null, primary key
#  code        :integer
#  tour_name   :string(255)
#  start_date  :date
#  end_date    :date
#  organizer   :string(255)
#  destination :string(255)
#  trip_type   :string(255)
#  trip_status :string(255)
#  planner_id  :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Trip < ActiveRecord::Base
  attr_accessible :code, :destination, :end_date, :organizer, :start_date, :tour_name, :trip_status, :trip_type

  belongs_to :planner

  def trip_duration(start_date = Date.today, end_date = Date.today)
    duration = end_date - start_date
    return duration
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @trip = Trip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(params[:trip])

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render json: @trip, status: :created, location: @trip }
      else
        format.html { render action: "new" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.haml
.row
  .span6.offset3
    = form_for(@trip) do |f|
      - if @trip.errors.any?
        #error_explanation
          %h2
            = pluralize(@trip.errors.count, "error")
            prohibited this trip from being saved:
          %ul
            - @trip.errors.full_messages.each do |msg|
              %li= msg
      = f.label :code
      %br/
      = f.number_field :code
      = f.label :tour_name
      %br/
      = f.text_field :tour_name
      = f.label :start_date
      %br/
      = f.date_select :start_date
      = f.label :end_date
      %br/
      = f.date_select :end_date
      = f.label :organizer
      %br/
      = f.text_field :organizer
      = f.label :destination
      %br/
      = f.text_field :destination
      = f.label :trip_type
      %br/
      = f.text_field :trip_type
      = f.label :trip_status
      %br/
      = f.text_field :trip_status
      = f.submit "Create Trip", class: "btn btn-medium btn-primary"

app/views/trips/edit.html.haml
%h1 Editing trip
= render 'form'
= link_to 'Show', @trip
|
\#{link_to 'Back', trips_path}

app/views/trips/index.html.haml
%h1 Listing trips
%table{:id => "trips", :class => "display"}
  %thead
    %tr
      %th Code
      %th Tour name
      %th Start date
      %th End date
      %th Organizer
      %th Destination
      %th Trip Type
      %th Trip Status
      %th Actions

  %tbody
    - @trips.each do |trip|
      %tr
        %td= trip.code
        %td= trip.tour_name
        %td= trip.start_date
        %td= trip.end_date
        %td= trip.organizer
        %td= trip.destination
        %td= trip.trip_type
        %td= trip.trip_status
        %td
          = link_to 'Show', trip
          |
          = link_to 'Edit', edit_trip_path(trip)
          |
          = link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Trip', new_trip_path, class: "btn btn-medium btn-secondary"

app/views/trips/new.html.haml
%h1 Create a New trip
= render 'form'
= link_to 'Back', trips_path, class: "btn btn-medium btn-primary"

app/views/trips/show.html.haml
%p#notice= notice
%p
  %b Code:
  = @trip.code
%p
  %b Tour name:
  = @trip.tour_name
%p
  %b Start date:
  = @trip.start_date
%p
  %b End date:
  = @trip.end_date
%p
  %b Organizer:
  = @trip.organizer
%p
  %b Destination:
  = @trip.destination
%p
  %b Trip type:
  = @trip.trip_type
%p
  %b Trip status:
  = @trip.trip_status
= link_to 'Edit', edit_trip_path(@trip)
|
\#{link_to 'Back', trips_path}