config/routes.rb
TripPlanner::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  root to: 'entrances#home'

  match '/about', to: 'entrances#about'
  match '/contact', to: 'entrances#contact'

  resources :organizations

  resources :planners

  resources :trips

end

app/models/planner.rb
# == Schema Information
#
# Table name: planners
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  organization_id :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Planner < ActiveRecord::Base
  attr_accessible :email, :name

  before_save {|user| user.email == email.downcase}
  has_many :trips
  belongs_to :organization

  validates :name, :presence => true, :uniqueness => true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
end

app/controllers/planners_controller.rb
class PlannersController < ApplicationController
  # GET /planners
  # GET /planners.json
  def index
    @planners = Planner.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @planners }
    end
  end

  # GET /planners/1
  # GET /planners/1.json
  def show
    @planner = Planner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @planner }
    end
  end

  # GET /planners/new
  # GET /planners/new.json
  def new
    @planner = Planner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @planner }
    end
  end

  # GET /planners/1/edit
  def edit
    @planner = Planner.find(params[:id])
  end

  # POST /planners
  # POST /planners.json
  def create
    @planner = Planner.new(params[:planner])

    respond_to do |format|
      if @planner.save
        format.html { redirect_to @planner, notice: 'Planner was successfully created.' }
        format.json { render json: @planner, status: :created, location: @planner }
      else
        format.html { render action: "new" }
        format.json { render json: @planner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /planners/1
  # PUT /planners/1.json
  def update
    @planner = Planner.find(params[:id])

    respond_to do |format|
      if @planner.update_attributes(params[:planner])
        format.html { redirect_to @planner, notice: 'Planner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @planner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planners/1
  # DELETE /planners/1.json
  def destroy
    @planner = Planner.find(params[:id])
    @planner.destroy

    respond_to do |format|
      format.html { redirect_to planners_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/planners_helper.rb
module PlannersHelper
end

app/views/planners/_form.html.haml
.row
  .span6.offset3
    = form_for(@planner) do |f|
      - if @planner.errors.any?
        #error_explanation
          %h2
            = pluralize(@planner.errors.count, "error")
            prohibited this planner from being saved:
          %ul
            - @planner.errors.full_messages.each do |msg|
              %li= msg
      = f.label :name
      = f.text_field :name
      = f.label :email
      = f.text_field :email
      = f.submit "Create planner", class: "btn btn-large btn-primary"

app/views/planners/edit.html.haml
%h1 Editing planner
= render 'form'
= link_to 'Show', @planner, class: "btn btn-large btn-primary"
|
\#{link_to 'Back', planners_path, class: "btn btn-large btn-primary"}

app/views/planners/index.html.haml
%h1 All planners
%table
  %tr
    %th Name
    %th Email
    %th
    %th
    %th
  - @planners.each do |planner|
    %tr
      %td= planner.name
      %td= planner.email
      %td= link_to 'Show', planner
      %td= link_to 'Edit', edit_planner_path(planner)
      %td= link_to 'Destroy', planner, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Planner', new_planner_path

app/views/planners/new.html.haml
%h1 New planner
= render 'form'
= link_to 'Back', planners_path, class: "btn btn-large btn-primary"

app/views/planners/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @planner.name
%p
  %b Email:
  = @planner.email
= link_to 'Edit', edit_planner_path(@planner), class: "btn btn-large btn-primary"
|
\#{link_to 'Back', planners_path, class: "btn btn-large btn-primary"}