config/routes.rb
TripPlanner::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  root to: 'entrances#home'

  match '/about', to: 'entrances#about'
  match '/contact', to: 'entrances#contact'

  resources :organizations

  resources :planners

  resources :trips

end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  address    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Organization < ActiveRecord::Base
  attr_accessible :address, :name

  has_many :planners

  validates :name, :presence => true, :uniqueness => true
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.haml
.row
  .span6.offset3
    = form_for(@organization) do |f|
      - if @organization.errors.any?
        #error_explanation
          %h2
            = pluralize(@organization.errors.count, "error")
            prohibited this organization from being saved:
          %ul
            - @organization.errors.full_messages.each do |msg|
              %li= msg
      = f.label :name
      %br/
      = f.text_field :name
      = f.label :address
      %br/
      = f.text_field :address
      = f.submit "Create Organization", class: "btn btn-large btn-primary"

app/views/organizations/edit.html.haml
%h1 Editing organization
= render 'form'
= link_to 'Show', @organization, class: "btn btn-large btn-primary"
|
\#{link_to 'Back', organizations_path, class: "btn btn-large btn-primary"}

app/views/organizations/index.html.haml
%h1 Listing organizations
%table
  %tr
    %th Name
    %td
    %th Address
    %th
    %th
    %th
  - @organizations.each do |organization|
    %tr
      %td= organization.name
      %td
      %td= organization.address
      %td
      %td= link_to 'Show', organization
      %td
      %td= link_to 'Edit', edit_organization_path(organization)
      %td
      %td= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Organization', new_organization_path, class: "btn btn-large btn-primary"

app/views/organizations/new.html.haml
%h1 New organization
= render 'form'
= link_to 'Back', organizations_path, class: "btn btn-large btn-primary"

app/views/organizations/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @organization.name
%p
  %b Address:
  = @organization.address
= link_to 'Edit', edit_organization_path(@organization)
|
\#{link_to 'Back', organizations_path}