config/routes.rb
TripPlanner::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  root to: 'entrances#home'

  match '/about', to: 'entrances#about'
  match '/contact', to: 'entrances#contact'

  resources :organizations

  resources :planners

  resources :trips

end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    Trip Planner by Janmejay Rai
  %nav
    %ul
      %li= link_to "About",   about_path
      %li= link_to "Contact", contact_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "Travel Planner", root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Home", root_path
          - if signed_in?
            %li= link_to "Users", users_path
            %li= link_to "Planners", planners_path
            %li= link_to "Organizations", organizations_path
            %li= link_to "Trips", trips_path
            %li#fat-menu.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li= link_to "Sign out", signout_path, method: "delete"
          - else
            %li= link_to "Sign in", signin_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TripPlanner
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        %div{:class => "alert alert-#{key}"}= value
      = yield
      = render 'layouts/footer'